### PR TITLE
Substitution of setInterval() with a signal sent by websockets

### PR DESCRIPTION
**Pull request by emrojo**

### CODE REVIEW

**Comment by NikolausC** [comment]
pending bugfix

**Comment by pjvv** [comment]
Is it possible to write some tests for this? I assume if it breaks we won't notice immediately unless the console is open?

**Comment by NikolausC** [comment]
If the Study Management app dies, the user will forever see a loading icon after clicking on a node. Could we show an error if it can't make a connection after a certain amount of time?

It doesn't seem to be showing the sub-cost codes when viewing a sub-project, unless you've updated it in that session

**Comment by NikolausC** [comment]
The error that shows data release is unavailable is different for sub-projects vs projects. On a sub-project it'll show the user-friendly error, but on a parent project it'll show HTTP 404.

Sub-costcode selection is disabled on sub-projects if the billing service is unavailable, but you can still change the cost cost on project nodes. You're only told it's unavailable when you're trying to save the project node.

**Comment by emrojo** [comment]
The sub costcode options are obtained directly from the billing service, that's why is disabled when opening a subproject, as there are no options to display.
In the project nodes you are able to edit the cost code because in any case it will need to check the cost code with the billing service in the moment you want to update it. The only check that could be added would be to check the billing service is available when the dialog is open, but I think it does not add any information useful. The billing service could be perfectly fine on that moment, and on update could be down, or viceversa.

**Pull request merged**
